name: CICD

on:
  push:
    branches: [main]
    
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build docker image
        run: docker build -t angelhigueros/relish-technical-test .

      - name: Publish image to docker hub
        run: docker push angelhigueros/relish-technical-test:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Pull image from docker hub
        run: docker pull angelhigueros/relish-technical-test:latest
      - name: Delete old container
        run: docker rm -f relish-technical-test
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name relish-technical-test angelhigueros/relish-technical-test